name: nkh-test
favicon: null
layout_spectrum: 0.73353
typography_spectrum: 0.51397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f50000'
    - '#cd7700'
    - '#304645'
    - '#5d9abd'
    - '#efff00'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
